---
title: "Change background ggplot"
author: "Chiara"
date: "October 3, 2015"
output: html_document
---


[GGplot 2 Geoms](http://docs.ggplot2.org/current/)

[GGplot 2 Themes](http://docs.ggplot2.org/dev/vignettes/themes.html)
 
```{r}

## Load ggplot
library(ggplot2)

##Load the dataframe
pf = read.csv("C:/Users/cdiloreto/Google Drive/Programming/Data sets and exercises/pseudo_facebook.tsv", sep = "\t")

## Sample qplot
qplot(x = www_likes, data = subset(pf, !is.na(gender)),
      color = I("black"), fill = gender) +
  scale_x_continuous(limits = c(0, 10), breaks = seq(0, 10, 1)) +
  scale_x_log10()

## Change background to white

qplot(x = www_likes, data = subset(pf, !is.na(gender)),
      color = I("black"), fill = gender) +
  scale_x_continuous(limits = c(0, 10), breaks = seq(0, 10, 1)) +
  scale_x_log10() +
  theme_bw()


## Remove grid
qplot(x = www_likes, data = subset(pf, !is.na(gender)),
      color = I("black"), fill = gender) +
  scale_x_continuous(limits = c(0, 10), breaks = seq(0, 10, 1)) +
  scale_x_log10() +
  theme(plot.background = element_blank(),
   panel.grid.major = element_blank(),
   panel.grid.minor = element_blank(),
   panel.border = element_blank())
  
## Draw axis
qplot(x = www_likes, data = subset(pf, !is.na(gender)),
      color = I("black"), fill = gender) +
  scale_x_continuous(limits = c(0, 10), breaks = seq(0, 10, 1)) +
  scale_x_log10() +
theme(axis.line = element_line(color = 'black'))

```

Color palettes
```{r}
##### color Palettes
## personalized
mycolors = c("#33CC33","#FF0000","#4D70DB","yellow")

## with black
cbbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

## with grey
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

# ggplot (...) +
  
# scale_fill_manual(values = mycolors) + 
#   theme(plot.title = element_text(lineheight=.8, face="bold"))

```

**Create a standard theme!**
```{r}

library(ggplot2)
data(diamonds)
library(dplyr)
diamonds_by_cut = group_by(diamonds, cut)
diamonds_mp_by_cut = summarise(diamonds_by_cut, mean_price = mean(price))


#personalized themes
mytheme = theme(plot.title = element_text(lineheight = 1.2, face = "bold"),
          panel.background = element_rect(fill = "lightblue"))


minimal_theme = theme(plot.title = element_text(lineheight=.8, face="bold"),
        panel.background = element_rect(fill = "white"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank())


    
ggplot(aes(x = cut, y = mean_price), data = diamonds_mp_by_cut) +
    geom_bar(stat = "identity", fill = "red") +
  theme(
    axis.text = element_text(size = 14),
    legend.key = element_rect(fill = "grey40"),
    legend.background = element_rect(fill = "white"),
    legend.position = c(0.14, 0.80),
    panel.grid.major = element_line(colour = "white"),
    panel.grid.minor = element_blank(),
    panel.background = element_rect(fill = "navy")
  )

ggplot(aes(x = cut, y = mean_price), data = diamonds_mp_by_cut) +
    geom_bar(stat = "identity", fill = "red") +
    labs(title = "Price by cut",
          y = "Mean") +
    mytheme
```

