---
title: "Plot Two Variables"
author: "Chiara"
started: "October 3, 2015"
output: html_document
---

#Data Analysis with R
##Udacity course
[Click here](https://www.udacity.com/me#!/) for Udacity courses 

Load the diamonds dataset (in ggplot)
```{r}
library(ggplot2)
data(diamonds)

##Count how many observations
nrow(diamonds)

##Count how many variables in the dataset
ncol(diamonds)
length(as.list(names(diamonds)))

## Structure of color variable
str(diamonds$color)

## Plot price of diamonds
qplot(x = price, data = diamonds,
      color = I("black"), fill = I("blue"))

## Summary of price
summary(diamonds$price)

##How many diamonds cost less than 500$
nrow(subset(diamonds, price < 500))

##How many diamonds cost less than 250$
nrow(subset(diamonds, price < 250))

##How many diamonds cost $15,000 or more
nrow(subset(diamonds, price >= 15000))

```

Exercise:
```{r}
# Explore the largest peak in the
# price histogram you created earlier.
qplot(x = price, data = diamonds,
      color = I("black"), fill = I("blue"))
      
# Try limiting the x-axis, altering the bin width,
# and setting different breaks on the x-axis.
qplot(x = price, data = diamonds,
      color = I("black"), fill = I("blue"),
      binwidth = 50) +
      scale_x_continuous(breaks = seq(250, 1250, 50)) +
      coord_cartesian(xlim = c(250,1250))


# You can save images by using the ggsave() command.
# ggsave() will save the last plot created.
# For example...
#                  qplot(x = price, data = diamonds)
#                  ggsave('priceHistogram.png')

# ggsave currently recognises the extensions eps/ps, tex (pictex),
# pdf, jpeg, tiff, png, bmp, svg and wmf (windows only).

```


```{r}
# Break out the histogram of diamond prices by cut.
qplot(x = price, data = diamonds,
      color = I("black"), fill = I("blue"))

# You should have five histograms in separate
# panels on your resulting plot.

# Basic histogram
qplot(x = price, data = diamonds,
      color = I("black"), fill = I("blue"))

# Analyze cut
levels(diamonds$cut)

# By function to check price split over cut
by(diamonds$price, diamonds$cut, summary)


# TYPE YOUR CODE BELOW THE LINE
# ======================================================
qplot(x = price, data = diamonds,
      color = I("black"), fill = I("blue")) +
  facet_wrap(~cut) +
  coord_cartesian(xlim = c(0, 5000))

```

```{r}
## Which cut has the highest price diamond?
by(diamonds$price, diamonds$cut, max)

## Which cut has the lowest price diamond?
by(diamonds$price, diamonds$cut, min)

## Which cut has the lowest mean for price?
by(diamonds$price, diamonds$cut, mean)

## Function `summary()` uses approximation
by(diamonds$price, diamonds$cut, summary)

```

```{r}
# In the two last exercises, we looked at
# the distribution for diamonds by cut.

# Run the code below in R Studio to generate
# the histogram as a reminder.

# ===============================================================

qplot(x = price, data = diamonds) + facet_wrap(~cut)
                                                                               
# ===============================================================

# In the last exercise, we looked at the summary statistics
# for diamond price by cut. If we look at the output table, the
# the median and quartiles are reasonably close to each other.

# diamonds$cut: Fair
#    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#     337    2050    3282    4359    5206   18570 
# ------------------------------------------------------------------------ 
# diamonds$cut: Good
#    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#     327    1145    3050    3929    5028   18790 
# ------------------------------------------------------------------------ 
# diamonds$cut: Very Good
#    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#     336     912    2648    3982    5373   18820 
# ------------------------------------------------------------------------ 
# diamonds$cut: Premium
#    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#     326    1046    3185    4584    6296   18820 
# ------------------------------------------------------------------------ 
# diamonds$cut: Ideal
#    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#     326     878    1810    3458    4678   18810 

# This means the distributions should be somewhat similar,
# but the histograms we created don't show that.

# The 'Fair' and 'Good' diamonds appear to have 
# different distributions compared to the better
# cut diamonds. They seem somewhat uniform
# on the left with long tails on the right.

# Let's look in to this more.

# Look up the documentation for facet_wrap in R Studio.
# Then, scroll back up and add a parameter to facet_wrap so that
# the y-axis in the histograms is not fixed. You want the y-axis to
# be different for each histogram.

qplot(x = price, data = diamonds) + facet_wrap(~cut, scales  = "free_y")

```

```{r}
# Create a histogram of price per carat
# and facet it by cut. You can make adjustments
# to the code from the previous exercise to get
# started.
qplot(x = price, y = carat, data = diamonds) + 
  facet_wrap(~cut, scales  = "free_y")


# Adjust the bin width and transform the scale
# of the x-axis using log10.
qplot(x = price, y = carat, data = diamonds,
      binwidth = 500) + 
  scale_x_log10() +
  facet_wrap(~cut, scales  = "free_y")

```

```{r}

# Investigate the price of diamonds using box plots,
# numerical summaries, and one of the following categorical
# variables: cut, clarity, or color.

# Boxplot
qplot(x = cut, y = price, data = diamonds,
      binwidth = 500, geom = "boxplot") +
  coord_cartesian(ylim = c(0, 7500))

# Numerical summaries
by(diamonds$price, diamonds$color, summary)
by(diamonds$price, diamonds$clarity, summary)

# You can save images by using the ggsave() command.
# ggsave() will save the last plot created.
# For example...
#                  qplot(x = price, data = diamonds)
#                  ggsave('priceHistogram.png')

```

```{r}
## Quartiles
by(diamonds$price, diamonds$color, IQR)

by(diamonds$price, diamonds$color, summary)

## Analyze price per carat faceted by cut
qplot(x = carat, y = price, data = diamonds, geom = "boxplot") +
  coord_cartesian(ylim = c(0, 7500)) +
  facet_wrap(~cut, scale = "free_x")

# Investigate the price per carat of diamonds across
# the different colors of diamonds using boxplots.
qplot(x = carat, y = price, data = diamonds, geom = "boxplot") +
  coord_cartesian(ylim = c(0, 8000)) +
  facet_wrap(~color, scale = "free_x",nrow = 2)

# Hint: Use price and carat as a ratio in the parameter y to create the box plots.
qplot(x = color, y = price/carat, data = diamonds, geom = "boxplot") +
  coord_cartesian(ylim = c(0, 6000)) +
  facet_wrap(~color, scale = "free_x",nrow = 2)

```

